=begin
#Aspose.ThreeD Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.11-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AsposeThreeDCloud::FileSystem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FileSystem' do
  before do
    # run before each test
    @instance = AsposeThreeDCloud::FileSystem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileSystem' do
    it 'should create an instance of FileSystem' do
      expect(@instance).to be_instance_of(AsposeThreeDCloud::FileSystem)
    end
  end
  describe 'test attribute "file_system_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "directory"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

