=begin
#Aspose.ThreeD Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.11-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AsposeThreeDCloud::PdfRenderMode
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PdfRenderMode' do
  before do
    # run before each test
    @instance = AsposeThreeDCloud::PdfRenderMode.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PdfRenderMode' do
    it 'should create an instance of PdfRenderMode' do
      expect(@instance).to be_instance_of(AsposeThreeDCloud::PdfRenderMode)
    end
  end
end

