=begin
#Aspose.3D Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.11-SNAPSHOT

=end

require 'date'

module AsposeThreeDCloud
  module PdfLightingScheme
    Artwork = 0,
    None = 1,
    White = 2,
    Day = 3,
    Night = 4,
    Hard = 5,
    Primary = 6,
    Blue = 7,
    Red = 8,
    Cube = 9,
    CAD = 10,
    Headlamp = 11
  end

end
