=begin
#Aspose.3D Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.11-SNAPSHOT

=end

require 'date'

module AsposeThreeDCloud
  module PdfRenderMode
    Solid = 0,
    SolidWireframe = 1,
    Transparent = 2,
    TransparentWireframe =3,
    BoundingBox=4,
    TransparentBoundingBox=5,
    TransparentBoundingBoxOutline=6,
    Wireframe=7,
    ShadedWireframe=8,
    HiddenWireframe=9,
    Vertices=10,
    ShadedVertices=11,
    Illustration=12,
    SolidOutline=13,
    ShadedIllustration=14
  end

end
