=begin
#Aspose.ThreeD Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.11-SNAPSHOT

=end

require 'date'

module AsposeThreeDCloud

  class PlySaveOption
    # Gets or sets  of the SaveFormat.
    attr_accessor :save_format

    # Allow user to handle how to manage the external dependencies during load/save.
    attr_accessor :file_system

    # Some files like OBJ depends on external file, the lookup paths will allows Aspose.3D to look for external file to load
    attr_accessor :lookup_paths

    # The file name of the exporting/importing scene. This is optional, but useful when serialize external assets like OBJ's material.
    attr_accessor :file_name

    # The file format��like FBX,U3D,PDF ....
    attr_accessor :file_format

    # Only for LocalFileSystem
    attr_accessor :directory

    # Flip the coordinate while saving the scene, default value is true.
    attr_accessor :flip_coordinate

    # The element name for the vertex data, default value is \"vertex\".
    attr_accessor :vertex_element

    # The component names for position data, default value is (\"x\", \"y\", \"z\")
    attr_accessor :position_components

    # The element name for the face data, default value is face.
    attr_accessor :face_element

    # The property name for the face data, default value is vertex_index.
    attr_accessor :face_property

    # Gets or sets  of the FileContent Style.
    attr_accessor :file_content_type


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'save_format' => :'SaveFormat',
        :'file_system' => :'FileSystem',
        :'lookup_paths' => :'LookupPaths',
        :'file_name' => :'FileName',
        :'file_format' => :'FileFormat',
        :'directory' => :'directory',
        :'flip_coordinate' => :'FlipCoordinate',
        :'vertex_element' => :'VertexElement',
        :'position_components' => :'PositionComponents',
        :'face_element' => :'FaceElement',
        :'face_property' => :'FaceProperty',
        :'file_content_type' => :'FileContentType'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'save_format' => :'SaveFormat',
        :'file_system' => :'FileSystem',
        :'lookup_paths' => :'Array<String>',
        :'file_name' => :'String',
        :'file_format' => :'String',
        :'directory' => :'String',
        :'flip_coordinate' => :'BOOLEAN',
        :'vertex_element' => :'String',
        :'position_components' => :'Array<String>',
        :'face_element' => :'String',
        :'face_property' => :'String',
        :'file_content_type' => :'FileContentType'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'SaveFormat')
        self.save_format = attributes[:'SaveFormat']
      end

      if attributes.has_key?(:'FileSystem')
        self.file_system = attributes[:'FileSystem']
      end

      if attributes.has_key?(:'LookupPaths')
        if (value = attributes[:'LookupPaths']).is_a?(Array)
          self.lookup_paths = value
        end
      end

      if attributes.has_key?(:'FileName')
        self.file_name = attributes[:'FileName']
      end

      if attributes.has_key?(:'FileFormat')
        self.file_format = attributes[:'FileFormat']
      end

      if attributes.has_key?(:'directory')
        self.directory = attributes[:'directory']
      end

      if attributes.has_key?(:'FlipCoordinate')
        self.flip_coordinate = attributes[:'FlipCoordinate']
      end

      if attributes.has_key?(:'VertexElement')
        self.vertex_element = attributes[:'VertexElement']
      end

      if attributes.has_key?(:'PositionComponents')
        if (value = attributes[:'PositionComponents']).is_a?(Array)
          self.position_components = value
        end
      end

      if attributes.has_key?(:'FaceElement')
        self.face_element = attributes[:'FaceElement']
      end

      if attributes.has_key?(:'FaceProperty')
        self.face_property = attributes[:'FaceProperty']
      end

      if attributes.has_key?(:'FileContentType')
        self.file_content_type = attributes[:'FileContentType']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          save_format == o.save_format &&
          file_system == o.file_system &&
          lookup_paths == o.lookup_paths &&
          file_name == o.file_name &&
          file_format == o.file_format &&
          directory == o.directory &&
          flip_coordinate == o.flip_coordinate &&
          vertex_element == o.vertex_element &&
          position_components == o.position_components &&
          face_element == o.face_element &&
          face_property == o.face_property &&
          file_content_type == o.file_content_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [save_format, file_system, lookup_paths, file_name, file_format, directory, flip_coordinate, vertex_element, position_components, face_element, face_property, file_content_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = AsposeThreeDCloud.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
