=begin
#Aspose.3D Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.11-SNAPSHOT

=end

require 'date'

module AsposeThreeDCloud
  module SaveFormat
    AMF = 0,
    ASE = 1,
    Aspose3DWeb = 2,
    Collada = 3,
    Discreet3DS = 4,
    Draco = 5,
    DXF = 6,
    FBX = 7,
    GLTF = 8,
    HTML = 9,
    JT = 10,
    Microsoft3MF = 11,
    Obj = 12,
    PDF = 13,
    PLY = 14,
    Rvm = 15,
    STL = 16,
    U3D = 17,
    VRML = 18,
    X = 19
  end

end
