=begin
#Aspose.ThreeD Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 3.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.11-SNAPSHOT

=end

require 'date'

module AsposeThreeDCloud
  module SaveFormat
    AMF  = 0,
    Collada = 1,
    Discreet3DS = 2,
    Draco = 3,
    FBX = 4,
    GLTF = 5,
    Obj = 6,
    PDF = 7,
    PLY = 8,
    Rvm = 9,
    STL = 10,
    USD = 11
=begin
    SaveFormatEnum = [AMF  = 0,
                      Collada = 1,
                      Discreet3DS = 2,
                      Draco = 3,
                      FBX = 4,
                      GLTF = 5,
                      Obj = 6,
                      PDF = 7,
                      PLY = 8,
                      Rvm = 9,
                      STL = 10,
                      USD = 11
    ]
=end


  end

end
